### ISSUE TITLE
🚊🚊🚊🚊🚊🚊🚊🚊🚊🚊🚊🚊🚊🚊🚊🚊🚊🚊🚊🚊

### ISSUE THREAD

**Issue by parnuxa** [MineDen/TS2D-Project#3]
ЗNaNётЁ о чєМ R мЭчtåю??? 👭🚊😍😳👉👌👅👅👅👅👅👅👅

**Comment by MineDen** [comment]
_What are you reporting_? **Bug** or **feature request**?

**Comment by parnuxa** [comment]
Feature request!

**Comment by MineDen** [comment]
What you _wish_ to **add**?

**Comment by parnuxa** [comment]
Gay couples on the stops

**Comment by MineDen** [comment]
### TS2D Feature request: _Answer to_ @parnuxa
---
TramSimulator2D is not LGBT-oriented game. But you can fork it, because TS2D are open source game!

**Comment by parnuxa** [comment]
Can you add the sparks??

**Comment by MineDen** [comment]
@parnuxa, on **pantograph**? Or add more **animations**?

**Comment by parnuxa** [comment]
Do you want to add tram kissing possibility?

**Comment by parnuxa** [comment]
Add more particles

**Comment by MineDen** [comment]
I want to add _**[PvP mode](https://en.wikipedia.org/wiki/Player_versus_player)**_ in versions **0.5.1** - **0.6.4**

**Comment by MineDen** [comment]
> Add more _particles_

@parnuxa, _particles_ to be used in [**_PvP mode_**](https://en.wikipedia.org/wiki/Player_versus_player), when _player_ wins.

**Comment by parnuxa** [comment]
And i want some kisses😗🚊

**Comment by MineDen** [comment]
**J^E(GE4&*&$%&*****%#!VF&GX((OF**CE_#^_&
