### ISSUE TITLE
👅(і)

### ISSUE THREAD

**Issue by parnuxa** [MineDen/TS2D-Project#6]

**Comment by parnuxa** [comment]
😳

**Comment by MineDen** [comment]
What is it? _Feature request_ or _bug report_?

**Comment by parnuxa** [comment]
This is bug report.

**Comment by parnuxa** [comment]
I can't see some objects

**Comment by MineDen** [comment]
In which **version** you see this _bug_?

**Comment by parnuxa** [comment]
In all versions

**Comment by MineDen** [comment]
What is **objects** that you cannot see?

**Comment by parnuxa** [comment]
Sparks, shit on cars, suicide on the rails, and one important thing - PUSSY TO LICK.

**Comment by MineDen** [comment]
@parnuxa :/ , you can **fork** or **clone** TS2D game and create your own version with all about you say.

**Comment by parnuxa** [comment]
I also dont see **gay trams**.

**Comment by MineDen** [comment]
@parnuxa, creating a **tram** is very _[lightweight process](ts2dproject.at.ua/ts2d_creatingtram.html)_.
